/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPalletTypesImport } from './routes/_authenticated/pallet-types'
import { Route as AuthenticatedPackagingTypesImport } from './routes/_authenticated/packaging-types'
import { Route as AuthenticatedMarketersImport } from './routes/_authenticated/marketers'
import { Route as AuthenticatedGrowersImport } from './routes/_authenticated/growers'
import { Route as AuthenticatedCustomerTypeImport } from './routes/_authenticated/customer-type'
import { Route as authSignInImport } from './routes/(auth)/sign-in'

// Create Virtual Routes

const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedPalletTypesRoute = AuthenticatedPalletTypesImport.update({
  id: '/pallet-types',
  path: '/pallet-types',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedPackagingTypesRoute =
  AuthenticatedPackagingTypesImport.update({
    id: '/packaging-types',
    path: '/packaging-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedMarketersRoute = AuthenticatedMarketersImport.update({
  id: '/marketers',
  path: '/marketers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedGrowersRoute = AuthenticatedGrowersImport.update({
  id: '/growers',
  path: '/growers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedCustomerTypeRoute = AuthenticatedCustomerTypeImport.update({
  id: '/customer-type',
  path: '/customer-type',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/customer-type': {
      id: '/_authenticated/customer-type'
      path: '/customer-type'
      fullPath: '/customer-type'
      preLoaderRoute: typeof AuthenticatedCustomerTypeImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/growers': {
      id: '/_authenticated/growers'
      path: '/growers'
      fullPath: '/growers'
      preLoaderRoute: typeof AuthenticatedGrowersImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/marketers': {
      id: '/_authenticated/marketers'
      path: '/marketers'
      fullPath: '/marketers'
      preLoaderRoute: typeof AuthenticatedMarketersImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/packaging-types': {
      id: '/_authenticated/packaging-types'
      path: '/packaging-types'
      fullPath: '/packaging-types'
      preLoaderRoute: typeof AuthenticatedPackagingTypesImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/pallet-types': {
      id: '/_authenticated/pallet-types'
      path: '/pallet-types'
      fullPath: '/pallet-types'
      preLoaderRoute: typeof AuthenticatedPalletTypesImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustomerTypeRoute: typeof AuthenticatedCustomerTypeRoute
  AuthenticatedGrowersRoute: typeof AuthenticatedGrowersRoute
  AuthenticatedMarketersRoute: typeof AuthenticatedMarketersRoute
  AuthenticatedPackagingTypesRoute: typeof AuthenticatedPackagingTypesRoute
  AuthenticatedPalletTypesRoute: typeof AuthenticatedPalletTypesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustomerTypeRoute: AuthenticatedCustomerTypeRoute,
  AuthenticatedGrowersRoute: AuthenticatedGrowersRoute,
  AuthenticatedMarketersRoute: AuthenticatedMarketersRoute,
  AuthenticatedPackagingTypesRoute: AuthenticatedPackagingTypesRoute,
  AuthenticatedPalletTypesRoute: AuthenticatedPalletTypesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/customer-type': typeof AuthenticatedCustomerTypeRoute
  '/growers': typeof AuthenticatedGrowersRoute
  '/marketers': typeof AuthenticatedMarketersRoute
  '/packaging-types': typeof AuthenticatedPackagingTypesRoute
  '/pallet-types': typeof AuthenticatedPalletTypesRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/': typeof AuthenticatedIndexRoute
}

export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/customer-type': typeof AuthenticatedCustomerTypeRoute
  '/growers': typeof AuthenticatedGrowersRoute
  '/marketers': typeof AuthenticatedMarketersRoute
  '/packaging-types': typeof AuthenticatedPackagingTypesRoute
  '/pallet-types': typeof AuthenticatedPalletTypesRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/': typeof AuthenticatedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/customer-type': typeof AuthenticatedCustomerTypeRoute
  '/_authenticated/growers': typeof AuthenticatedGrowersRoute
  '/_authenticated/marketers': typeof AuthenticatedMarketersRoute
  '/_authenticated/packaging-types': typeof AuthenticatedPackagingTypesRoute
  '/_authenticated/pallet-types': typeof AuthenticatedPalletTypesRoute
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/sign-in'
    | '/customer-type'
    | '/growers'
    | '/marketers'
    | '/packaging-types'
    | '/pallet-types'
    | '/forgot-password'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/customer-type'
    | '/growers'
    | '/marketers'
    | '/packaging-types'
    | '/pallet-types'
    | '/forgot-password'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/_authenticated/customer-type'
    | '/_authenticated/growers'
    | '/_authenticated/marketers'
    | '/_authenticated/packaging-types'
    | '/_authenticated/pallet-types'
    | '/(auth)/forgot-password'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/sign-in",
        "/(auth)/forgot-password"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/customer-type",
        "/_authenticated/growers",
        "/_authenticated/marketers",
        "/_authenticated/packaging-types",
        "/_authenticated/pallet-types",
        "/_authenticated/"
      ]
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/customer-type": {
      "filePath": "_authenticated/customer-type.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/growers": {
      "filePath": "_authenticated/growers.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/marketers": {
      "filePath": "_authenticated/marketers.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/packaging-types": {
      "filePath": "_authenticated/packaging-types.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/pallet-types": {
      "filePath": "_authenticated/pallet-types.tsx",
      "parent": "/_authenticated"
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
