/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPalletTypesImport } from './routes/_authenticated/pallet-types'
import { Route as AuthenticatedPackagingTypesImport } from './routes/_authenticated/packaging-types'
import { Route as AuthenticatedMarketersImport } from './routes/_authenticated/marketers'
import { Route as AuthenticatedGrowersImport } from './routes/_authenticated/growers'
import { Route as AuthenticatedCustomersImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCustomerTypeImport } from './routes/_authenticated/customer-type'
import { Route as AuthenticatedCalendarImport } from './routes/_authenticated/calendar'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedProducesIndexImport } from './routes/_authenticated/produces/index'
import { Route as AuthenticatedProducesProduceIdImport } from './routes/_authenticated/produces/$produceId'

// Create Virtual Routes

const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedPalletTypesRoute = AuthenticatedPalletTypesImport.update({
  id: '/pallet-types',
  path: '/pallet-types',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedPackagingTypesRoute =
  AuthenticatedPackagingTypesImport.update({
    id: '/packaging-types',
    path: '/packaging-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedMarketersRoute = AuthenticatedMarketersImport.update({
  id: '/marketers',
  path: '/marketers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedGrowersRoute = AuthenticatedGrowersImport.update({
  id: '/growers',
  path: '/growers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedCustomersRoute = AuthenticatedCustomersImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedCustomerTypeRoute = AuthenticatedCustomerTypeImport.update({
  id: '/customer-type',
  path: '/customer-type',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedCalendarRoute = AuthenticatedCalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedProducesIndexRoute = AuthenticatedProducesIndexImport.update(
  {
    id: '/produces/',
    path: '/produces/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedProducesProduceIdRoute =
  AuthenticatedProducesProduceIdImport.update({
    id: '/produces/$produceId',
    path: '/produces/$produceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/customer-type': {
      id: '/_authenticated/customer-type'
      path: '/customer-type'
      fullPath: '/customer-type'
      preLoaderRoute: typeof AuthenticatedCustomerTypeImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/growers': {
      id: '/_authenticated/growers'
      path: '/growers'
      fullPath: '/growers'
      preLoaderRoute: typeof AuthenticatedGrowersImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/marketers': {
      id: '/_authenticated/marketers'
      path: '/marketers'
      fullPath: '/marketers'
      preLoaderRoute: typeof AuthenticatedMarketersImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/packaging-types': {
      id: '/_authenticated/packaging-types'
      path: '/packaging-types'
      fullPath: '/packaging-types'
      preLoaderRoute: typeof AuthenticatedPackagingTypesImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/pallet-types': {
      id: '/_authenticated/pallet-types'
      path: '/pallet-types'
      fullPath: '/pallet-types'
      preLoaderRoute: typeof AuthenticatedPalletTypesImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/produces/$produceId': {
      id: '/_authenticated/produces/$produceId'
      path: '/produces/$produceId'
      fullPath: '/produces/$produceId'
      preLoaderRoute: typeof AuthenticatedProducesProduceIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/produces/': {
      id: '/_authenticated/produces/'
      path: '/produces'
      fullPath: '/produces'
      preLoaderRoute: typeof AuthenticatedProducesIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCustomerTypeRoute: typeof AuthenticatedCustomerTypeRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedGrowersRoute: typeof AuthenticatedGrowersRoute
  AuthenticatedMarketersRoute: typeof AuthenticatedMarketersRoute
  AuthenticatedPackagingTypesRoute: typeof AuthenticatedPackagingTypesRoute
  AuthenticatedPalletTypesRoute: typeof AuthenticatedPalletTypesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProducesProduceIdRoute: typeof AuthenticatedProducesProduceIdRoute
  AuthenticatedProducesIndexRoute: typeof AuthenticatedProducesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCustomerTypeRoute: AuthenticatedCustomerTypeRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedGrowersRoute: AuthenticatedGrowersRoute,
  AuthenticatedMarketersRoute: AuthenticatedMarketersRoute,
  AuthenticatedPackagingTypesRoute: AuthenticatedPackagingTypesRoute,
  AuthenticatedPalletTypesRoute: AuthenticatedPalletTypesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProducesProduceIdRoute: AuthenticatedProducesProduceIdRoute,
  AuthenticatedProducesIndexRoute: AuthenticatedProducesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/customer-type': typeof AuthenticatedCustomerTypeRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/growers': typeof AuthenticatedGrowersRoute
  '/marketers': typeof AuthenticatedMarketersRoute
  '/packaging-types': typeof AuthenticatedPackagingTypesRoute
  '/pallet-types': typeof AuthenticatedPalletTypesRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/produces/$produceId': typeof AuthenticatedProducesProduceIdRoute
  '/produces': typeof AuthenticatedProducesIndexRoute
}

export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/customer-type': typeof AuthenticatedCustomerTypeRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/growers': typeof AuthenticatedGrowersRoute
  '/marketers': typeof AuthenticatedMarketersRoute
  '/packaging-types': typeof AuthenticatedPackagingTypesRoute
  '/pallet-types': typeof AuthenticatedPalletTypesRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/produces/$produceId': typeof AuthenticatedProducesProduceIdRoute
  '/produces': typeof AuthenticatedProducesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/customer-type': typeof AuthenticatedCustomerTypeRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/growers': typeof AuthenticatedGrowersRoute
  '/_authenticated/marketers': typeof AuthenticatedMarketersRoute
  '/_authenticated/packaging-types': typeof AuthenticatedPackagingTypesRoute
  '/_authenticated/pallet-types': typeof AuthenticatedPalletTypesRoute
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/produces/$produceId': typeof AuthenticatedProducesProduceIdRoute
  '/_authenticated/produces/': typeof AuthenticatedProducesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/sign-in'
    | '/calendar'
    | '/customer-type'
    | '/customers'
    | '/growers'
    | '/marketers'
    | '/packaging-types'
    | '/pallet-types'
    | '/forgot-password'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/produces/$produceId'
    | '/produces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/calendar'
    | '/customer-type'
    | '/customers'
    | '/growers'
    | '/marketers'
    | '/packaging-types'
    | '/pallet-types'
    | '/forgot-password'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/produces/$produceId'
    | '/produces'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/_authenticated/calendar'
    | '/_authenticated/customer-type'
    | '/_authenticated/customers'
    | '/_authenticated/growers'
    | '/_authenticated/marketers'
    | '/_authenticated/packaging-types'
    | '/_authenticated/pallet-types'
    | '/(auth)/forgot-password'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/produces/$produceId'
    | '/_authenticated/produces/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/sign-in",
        "/(auth)/forgot-password",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/calendar",
        "/_authenticated/customer-type",
        "/_authenticated/customers",
        "/_authenticated/growers",
        "/_authenticated/marketers",
        "/_authenticated/packaging-types",
        "/_authenticated/pallet-types",
        "/_authenticated/",
        "/_authenticated/produces/$produceId",
        "/_authenticated/produces/"
      ]
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/calendar": {
      "filePath": "_authenticated/calendar.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/customer-type": {
      "filePath": "_authenticated/customer-type.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/customers": {
      "filePath": "_authenticated/customers.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/growers": {
      "filePath": "_authenticated/growers.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/marketers": {
      "filePath": "_authenticated/marketers.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/packaging-types": {
      "filePath": "_authenticated/packaging-types.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/pallet-types": {
      "filePath": "_authenticated/pallet-types.tsx",
      "parent": "/_authenticated"
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/produces/$produceId": {
      "filePath": "_authenticated/produces/$produceId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/produces/": {
      "filePath": "_authenticated/produces/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
